# Generated by Django 3.2.15 on 2022-09-07 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('miembros', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin_estimada', models.DateTimeField()),
                ('fecha_fin_real', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_PROCESO', 'En progreso'), ('TERMINADO', 'Terminado'), ('CANCELLED', 'Cancelado'), ('RETRASADO', 'Retrasado')], max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
            ],
        ),
    ]
