# Generated by Django 3.2.15 on 2022-10-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_PROCESO', 'En progreso'), ('TERMINADO', 'Terminado'), ('CANCELLED', 'Cancelado'), ('RETRASADO', 'Retrasado')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin_estimada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=100)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadous')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sprint')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipouserstory')),
            ],
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='estadous',
            name='tipoUserStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipouserstory'),
        ),
    ]
