# Generated by Django 3.2.15 on 2022-09-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='proyecto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='desconocido', max_length=100),
        ),
    ]
